apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-k8s
spec:
  selector:
    matchLabels:
      app: debug-kubernetes
  template:
    metadata:
      labels:
        app: debug-k8s
        service: debug-k8s
    spec:
      containers:
      - name: debug-k8s-latest
        image: moficodes/debugging-k8s:latest
        # imagePullPolicy: Always
        ports:
        - containerPort: 8000
