apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-k8s-deployment
spec:
  selector:
    matchLabels:
      app: debug-k8s
  template:
    metadata:
      labels:
        app: debug-k8s
    spec:
      containers:
      - name: debug-k8s
        image: moficodes/debugging-k8s:v0.0.5
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
